#!/bin/bash

# Use this if you want to append the current SHA to the doc pdf
#sha=$(git rev-parse HEAD)
#source proj_gen && weaver -o doc/MathLibrary.${sha:0:7}.pdf doc/root.mdl index.json

source proj_gen && weaver -o doc/MathLibrary.pdf doc/root.mdl index.json
