#!/bin/bash

mkdir -p build && cd build && cmake --preset clang-release .. && cd ..

local_dir=$(dirname "$0")

file_to_check="${local_dir}/sources.py"

if [ ! -f "$file_to_check" ]; then
  echo "Error: $file_to_check' not found. Rerun this script, or follow manual build instructions README.md"
  exit 1
fi

echo "$file_to_check exists, continuing..."

fragmenter -v --namespace_filter std,__gnu_cxx,ns -i index.json 